// Code generated by goctl. DO NOT EDIT.
package types

type CreateReq struct {
	Name string `json:"name"`
}

type CreateResp struct {
	Message string `json:"message"`
}

type Book struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type ReadBookByIdReq struct {
	Id int64 `path:"id"`
}

type ReadBookByIdResp struct {
	Book
}

type ReadBookByNameReq struct {
	Name string `form:"name"`
}

type ReadBookByNameResp struct {
	Book
}
