// Code generated by goctl. DO NOT EDIT.
package types

type CreateReq struct {
	Name string `json:"name"`
}

type CreateResp struct {
	Message string `json:"message"`
}

type ReadBookByNameReq struct {
	Name string `form:"name"`
}

type ReadBookByNameResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}
